# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_CITY_LAT
ARG NEXT_PUBLIC_CITY_LNG
ARG NEXT_PUBLIC_CITY_ZOOM
ARG NEXT_PUBLIC_GOOGLE_MAP_GESTURE_HANDLING
ARG NEXT_PUBLIC_GOOGLE_MAP_ID
ARG NEXT_PUBLIC_CITY_RESTRICTION_NORTH
ARG NEXT_PUBLIC_CITY_RESTRICTION_SOUTH
ARG NEXT_PUBLIC_CITY_RESTRICTION_WEST
ARG NEXT_PUBLIC_CITY_RESTRICTION_EAST
ARG NEXT_PUBLIC_API_BASE_URL
ARG API_BASE_URL
ARG NEXT_PUBLIC_WEB_SOCKET_BROKER_URL
ARG NEXT_PUBLIC_WEB_SOCKET_TRUCK_LOCATION_UPDATES_TOPIC
ARG NEXT_PUBLIC_FACEBOOK_LINK
ARG NEXT_PUBLIC_INSTAGRAM_LINK
ARG NEXT_PUBLIC_TWITTER_LINK
ARG NEXT_PUBLIC_YOUTUBE_LINK
ARG NEXT_PUBLIC_WEBSITE_LINK

ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_CITY_LAT=$NEXT_PUBLIC_CITY_LAT
ENV NEXT_PUBLIC_CITY_LNG=$NEXT_PUBLIC_CITY_LNG
ENV NEXT_PUBLIC_CITY_ZOOM=$NEXT_PUBLIC_CITY_ZOOM
ENV NEXT_PUBLIC_GOOGLE_MAP_GESTURE_HANDLING=$NEXT_PUBLIC_GOOGLE_MAP_GESTURE_HANDLING
ENV NEXT_PUBLIC_GOOGLE_MAP_ID=$NEXT_PUBLIC_GOOGLE_MAP_ID
ENV NEXT_PUBLIC_CITY_RESTRICTION_NORTH=$NEXT_PUBLIC_CITY_RESTRICTION_NORTH
ENV NEXT_PUBLIC_CITY_RESTRICTION_SOUTH=$NEXT_PUBLIC_CITY_RESTRICTION_SOUTH
ENV NEXT_PUBLIC_CITY_RESTRICTION_WEST=$NEXT_PUBLIC_CITY_RESTRICTION_WEST
ENV NEXT_PUBLIC_CITY_RESTRICTION_EAST=$NEXT_PUBLIC_CITY_RESTRICTION_EAST
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV API_BASE_URL=$API_BASE_URL
ENV NEXT_PUBLIC_WEB_SOCKET_BROKER_URL=$NEXT_PUBLIC_WEB_SOCKET_BROKER_URL
ENV NEXT_PUBLIC_WEB_SOCKET_TRUCK_LOCATION_UPDATES_TOPIC=$NEXT_PUBLIC_WEB_SOCKET_TRUCK_LOCATION_UPDATES_TOPIC
ENV NEXT_PUBLIC_FACEBOOK_LINK=$NEXT_PUBLIC_FACEBOOK_LINK
ENV NEXT_PUBLIC_INSTAGRAM_LINK=$NEXT_PUBLIC_INSTAGRAM_LINK
ENV NEXT_PUBLIC_TWITTER_LINK=$NEXT_PUBLIC_TWITTER_LINK
ENV NEXT_PUBLIC_YOUTUBE_LINK=$NEXT_PUBLIC_YOUTUBE_LINK
ENV NEXT_PUBLIC_WEBSITE_LINK=$NEXT_PUBLIC_WEBSITE_LINK

# Build the application
RUN pnpm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]